perf reg: Fix compilation error with GCC 10
Due to NULL being returned in default case GCC 10
is throwing below error. This is a temporary fix
for the S2 release.

In file included from /home/sgoutham/tools/marvell-tools-1010.0/aarch64-marvell-linux-gnu/sys-root/usr/include/stdio.h:867,
                 from /home/sgoutham/WORK/new/sunil/combined/5.4/linux/tools/perf/lib/include/perf/cpumap.h:6,
                 from util/session.c:13:
In function ‘printf’,
    inlined from ‘regs_dump__printf’ at util/session.c:1098:3,
    inlined from ‘regs__printf’ at util/session.c:1126:2:
/home/sgoutham/tools/marvell-tools-1010.0/aarch64-marvell-linux-gnu/sys-root/usr/include/bits/stdio2.h:107:10: error: ‘%-5s’ directive argument is null [-Werror=format-overflow=]
  107 |   return __printf_chk (__USE_FORTIFY_LEVEL - 1, __fmt, __va_arg_pack ());
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: Ib04ab83cccb00cf6439a75a5d0ef64973dffd02b
Signed-off-by: Sunil Goutham <sgoutham@marvell.com>
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/35922
Reviewed-by: Sunil Kovvuri Goutham <Sunil.Goutham@cavium.com>
Tested-by: Sunil Kovvuri Goutham <Sunil.Goutham@cavium.com>
(cherry picked from commit afff581bdec797a523eb6e9765a6fbe7c14eb79d)
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/kernel/linux/+/35967
[WK: The original patch got from Marvell sdk11.21.09]
Signed-off-by: Wenlin Kang <wenlin.kang@windriver.com>