can: flexcan: Fix compilation errors
commit c77b02d5c57c278416d5447d2867ce63940d6b8d from
https://source.codeaurora.org/external/imx/linux-imx.git

As per commit 'e05237f9da42 (can: flexcan: remove not needed struct
flexcan_priv::tx_mb and struct flexcan_priv::tx_mb_idx)', make changes to
fix the compilation error.

drivers/net/can/flexcan.c: In function ‘flexcan_start_xmit’:
drivers/net/can/flexcan.c:711:33: error: ‘const struct flexcan_priv’ has no member named ‘tx_mb_idx’
   flexcan_mb_write_le(priv, priv->tx_mb_idx,
                                 ^~
drivers/net/can/flexcan.c:720:32: error: ‘const struct flexcan_priv’ has no member named ‘tx_mb_idx’
  flexcan_mb_write_le(priv, priv->tx_mb_idx, FLEXCAN_MB_ID, can_id);
                                ^~
drivers/net/can/flexcan.c:721:32: error: ‘const struct flexcan_priv’ has no member named ‘tx_mb_idx’
  flexcan_mb_write_le(priv, priv->tx_mb_idx, FLEXCAN_MB_CTRL, ctrl);
                                ^~
drivers/net/can/flexcan.c: In function ‘flexcan_irq’:
drivers/net/can/flexcan.c:992:33: error: ‘struct flexcan_priv’ has no member named ‘tx_mb_idx’
   flexcan_mb_write_le(priv, priv->tx_mb_idx, FLEXCAN_MB_CTRL,
                                 ^~
drivers/net/can/flexcan.c: In function ‘flexcan_chip_start’:
drivers/net/can/flexcan.c:1231:16: error: ‘struct flexcan_priv’ has no member named ‘tx_mb_idx’
   for (i = priv->tx_mb_idx; i < priv->mb_num ; i++) {
                ^~
drivers/net/can/flexcan.c:1242:32: error: ‘struct flexcan_priv’ has no member named ‘tx_mb_idx’
  flexcan_mb_write_le(priv, priv->tx_mb_idx, FLEXCAN_MB_CTRL,
                                ^~
drivers/net/can/flexcan.c:1254:15: error: ‘struct flexcan_priv’ has no member named ‘tx_mb_idx’
  for (i = priv->tx_mb_idx; i < priv->mb_num ; i++)
               ^~
drivers/net/can/flexcan.c: In function ‘flexcan_probe’:
drivers/net/can/flexcan.c:1642:8: error: ‘struct flexcan_priv’ has no member named ‘tx_mb_idx’
    priv->tx_mb_idx = FLEXCAN_TX_MB_OFF_TIMESTAMP_FD;
        ^~
drivers/net/can/flexcan.c:1646:8: error: ‘struct flexcan_priv’ has no member named ‘tx_mb_idx’
    priv->tx_mb_idx = FLEXCAN_TX_MB_OFF_TIMESTAMP;
        ^~
drivers/net/can/flexcan.c:1646:22: error: ‘FLEXCAN_TX_MB_OFF_TIMESTAMP’ undeclared (first use in this function); did you mean ‘FLEXCAN_TX_MB_OFF_TIMESTAMP_FD’?
    priv->tx_mb_idx = FLEXCAN_TX_MB_OFF_TIMESTAMP;
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      FLEXCAN_TX_MB_OFF_TIMESTAMP_FD
drivers/net/can/flexcan.c:1646:22: note: each undeclared identifier is reported only once for each function it appears in
drivers/net/can/flexcan.c:1657:7: error: ‘struct flexcan_priv’ has no member named ‘tx_mb_idx’
   priv->tx_mb_idx = FLEXCAN_TX_MB_OFF_FIFO;
       ^~
drivers/net/can/flexcan.c:1657:21: error: ‘FLEXCAN_TX_MB_OFF_FIFO’ undeclared (first use in this function); did you mean ‘FLEXCAN_ESR_BOFF_INT’?
   priv->tx_mb_idx = FLEXCAN_TX_MB_OFF_FIFO;
                     ^~~~~~~~~~~~~~~~~~~~~~
                     FLEXCAN_ESR_BOFF_INT
scripts/Makefile.build:303: recipe for target 'drivers/net/can/flexcan.o' failed
make[3]: *** [drivers/net/can/flexcan.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>