media: v4l2-ioctl: replace IOCTL_INFO_FNC with stub function
commit 1014f65c402c897f0c2924f741b9b34a3130f78c from
https://source.codeaurora.org/external/imx/linux-imx.git

As per commit 3ad3b7a2ebae ("media: v4l2-ioctl: replace IOCTL_INFO_STD with
stub functions"), replace IOCTL_INFO_FNC with the IOCTL_INFO to fix the
compilation error.

drivers/media/v4l2-core/v4l2-ioctl.c:2684:2: error: implicit declaration of function ‘IOCTL_INFO_FNC’; did you mean ‘IOCTL_INFO’? [-Werror=implicit-function-declaration]
  IOCTL_INFO_FNC(VIDIOC_DBG_G_CHIP_IDENT, v4l_dbg_g_chip_ident, v4l_print_dbg_chip_ident, 0),
  ^~~~~~~~~~~~~~
  IOCTL_INFO
drivers/media/v4l2-core/v4l2-ioctl.c:2684:2: error: initializer element is not constant

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>