ASoC: fsl_spdif: fixed compilation errors
commit 4714a65358458362d8b4e641baf1f56c3b952830 from
https://source.codeaurora.org/external/imx/linux-imx.git

sound/soc/fsl/fsl_spdif.c: In function ‘fsl_spdif_set_dai_sysclk’:
sound/soc/fsl/fsl_spdif.c:811:6: error: implicit declaration of function ‘__clk_get_name’; did you mean ‘clk_get_rate’? [-Werror=implicit-function-declaration]
      __clk_get_name(npll), ret);
      ^~~~~~~~~~~~~~
./include/linux/device.h:1420:33: note: in definition of macro ‘dev_warn’
  _dev_warn(dev, dev_fmt(fmt), ##__VA_ARGS__)
                                 ^~~~~~~~~~~
sound/soc/fsl/fsl_spdif.c:810:6: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
      "failed to set parent %s: %d\n",
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/device.h:1335:22: note: in definition of macro ‘dev_fmt’
 #define dev_fmt(fmt) fmt
                      ^~~
sound/soc/fsl/fsl_spdif.c:809:5: note: in expansion of macro ‘dev_warn’
     dev_warn(cpu_dai->dev,
     ^~~~~~~~
At top level:
sound/soc/fsl/fsl_spdif.c:770:12: warning: ‘fsl_spdif_set_dai_sysclk’ defined but not used [-Wunused-function]
 static int fsl_spdif_set_dai_sysclk(struct snd_soc_dai *cpu_dai,
            ^~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_spdif.o' failed
make[3]: *** [sound/soc/fsl/fsl_spdif.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>