soc: ti: wkup_m3_ipc: fix compiling error for rproc
commit 1b20bb21a049fc5c4735639e64fe7afa3e8e727d from
https://git.ti.com/cgit/processor-sdk/processor-sdk-linux/?h=processor-sdk-linux-01.00.00

drivers/soc/ti/wkup_m3_ipc.c: In function 'wkup_m3_copy_aux_data':
drivers/soc/ti/wkup_m3_ipc.c:112:18: error: too few arguments to function 'rproc_da_to_va'
  aux_data_addr = rproc_da_to_va(m3_ipc->rproc,
                  ^~~~~~~~~~~~~~

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>