ASoC: fsl_asrc: fixed compilation error
commit 060950436d73a059e3a0851a82e6f06e39cef06a from
https://source.codeaurora.org/external/imx/linux-imx.git

sound/soc/fsl/fsl_asrc.c: In function ‘fsl_asrc_probe’:
sound/soc/fsl/fsl_asrc.c:1093:20: error: ‘struct fsl_asrc’ has no member named ‘name’
   strncpy(asrc_priv->name, "mxc_asrc",
                    ^~
sound/soc/fsl/fsl_asrc.c:1094:21: error: ‘struct fsl_asrc’ has no member named ‘name’
     sizeof(asrc_priv->name) - 1);
                     ^~
sound/soc/fsl/fsl_asrc.c:1099:20: error: ‘struct fsl_asrc’ has no member named ‘name’
   strncpy(asrc_priv->name, "mxc_asrc",
                    ^~
sound/soc/fsl/fsl_asrc.c:1100:21: error: ‘struct fsl_asrc’ has no member named ‘name’
     sizeof(asrc_priv->name) - 1);
                     ^~
sound/soc/fsl/fsl_asrc.c:1105:20: error: ‘struct fsl_asrc’ has no member named ‘name’
   strncpy(asrc_priv->name, "mxc_asrc",
                    ^~
sound/soc/fsl/fsl_asrc.c:1106:21: error: ‘struct fsl_asrc’ has no member named ‘name’
     sizeof(asrc_priv->name) - 1);
                     ^~
sound/soc/fsl/fsl_asrc.c:1111:20: error: ‘struct fsl_asrc’ has no member named ‘name’
   strncpy(asrc_priv->name, "mxc_asrc1",
                    ^~
sound/soc/fsl/fsl_asrc.c:1112:21: error: ‘struct fsl_asrc’ has no member named ‘name’
     sizeof(asrc_priv->name) - 1);
                     ^~
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_asrc.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>