Revert "platform/x86: Convert to new CPU match macros"
This reverts commit 6bb250d5703c54f40c1b3c10e06ba6000bffe9d2.

Revert this commit, as it introduced the following build failure:
|build/tmp-glibc/work-shared/intel-x86-64/kernel-source/drivers/platform/x86/intel_int0002_vgpio.c:60:47: error: 'int0002_byt_irqchip' undeclared here (not in a function)
| 60 | X86_MATCH_INTEL_FAM6_MODEL(ATOM_SILVERMONT, &int0002_byt_irqchip),
| | ^~~~~~~~~~~~~~~~~~~
| build/tmp-glibc/work-shared/intel-x86-64/kernel-source/arch/x86/include/asm/cpu_device_id.h:46:33: note: in definition of macro 'X86_MATCH_VENDOR_FAM_MODEL_FEATURE'
| 46 | .driver_data = (unsigned long) _data \
| | ^~~~~

Also, the SKYLAKE_L macros are not defined.

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>