ASoC: fsl_ssi: fixed compilation errors
commit fc8937a9b755cd608e39d20a71b861449ab0fb21 from
https://source.codeaurora.org/external/imx/linux-imx.git

As per commit 2474e4037c4e ("ASoC: fsl_ssi: Replace fsl_ssi_rxtx_reg_val
with fsl_ssi_regvals"), made changes to fix the compilation errors.

sound/soc/fsl/fsl_ssi.c: In function ‘fsl_ssi_hw_params’:
sound/soc/fsl/fsl_ssi.c:817:41: error: ‘struct fsl_ssi’ has no member named ‘rxtx_reg_val’
  struct fsl_ssi_rxtx_reg_val *reg = &ssi->rxtx_reg_val;
                                         ^~
sound/soc/fsl/fsl_ssi.c:879:7: error: dereferencing pointer to incomplete type ‘struct fsl_ssi_rxtx_reg_val’
    reg->rx.srcr &= ~SSI_SRCR_RFEN1;
       ^~
  AR      drivers/base/built-in.a
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_ssi.o' failed
make[3]: *** [sound/soc/fsl/fsl_ssi.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>