v4l: xilinx: hls: Fix the uapi header license
commit e57eff97a186b81f01f131c4d4c7b45cb1923f6e from
https://github.com/Xilinx/linux-xlnx.git

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Yaliang Wang <Yaliang.Wang@windriver.com>