media: hdr-ctrls: Add a missing include
commit 2247d223e3e4ba15020e80c26e4390dcab0c4fe6 from
https://github.com/Xilinx/linux-xlnx.git

The header has data types that have to be included from
types.h.

>> include/media/hdr-ctrls.h:59:2: error: unknown type name '__u8'
      59 |  __u8 eotf;
         |  ^~~~
...

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Reviewed-by: Dylan Yip <dylan.yip@xilinx.com>
State: pending
Signed-off-by: Yaliang Wang <Yaliang.Wang@windriver.com>