ASoC-fsl: fixed compilation error
commit f7298dc903402e0550555ceb0f292c9b902d849c from
https://source.codeaurora.org/external/imx/linux-imx.git

sound/soc/fsl/fsl_esai.c: In function ‘fsl_esai_probe’:
sound/soc/fsl/fsl_esai.c:1163:8: error: implicit declaration of function ‘imx_pcm_platform_register’; did you mean ‘imx_rpmsg_platform_register’? [-Werror=implicit-function-declaration]
  ret = imx_pcm_platform_register(&pdev->dev);
        ^~~~~~~~~~~~~~~~~~~~~~~~~
        imx_rpmsg_platform_register
  CC      fs/fat/inode.o
At top level:
sound/soc/fsl/fsl_esai.c:1170:12: warning: ‘fsl_esai_remove’ defined but not used [-Wunused-function]
 static int fsl_esai_remove(struct platform_device *pdev)
            ^~~~~~~~~~~~~~~
sound/soc/fsl/fsl_esai.c:741:12: warning: ‘fsl_esai_hw_free’ defined but not used [-Wunused-function]
 static int fsl_esai_hw_free(struct snd_pcm_substream *substream,
            ^~~~~~~~~~~~~~~~
  AR      sound/soc/codecs/built-in.a
  CC      drivers/base/core.o
  CC      drivers/base/bus.o
  CC      net/can/proc.o
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_esai.o' failed
make[3]: *** [sound/soc/fsl/fsl_esai.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/fsl' failed
make[2]: *** [sound/soc/fsl] Error 2
scripts/Makefile.build:546: recipe for target 'sound/soc' failed
make[1]: *** [sound/soc] Error 2
Makefile:1052: recipe for target 'sound' failed
make: *** [sound] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>