v4l: xilinx: csi: Fix the uapi header license
commit b0a14f9ed1184651fe7486b7e62d23b59833eeeb from
https://github.com/Xilinx/linux-xlnx.git

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Yaliang Wang <Yaliang.Wang@windriver.com>