ice: fix build errors when CONFIG_XDP_SOCKETS=y
The ice ethernet driver in LTS19 was updated to the 5.12 codebase in
LINUXEXEC-10558 and adjusted to match various 5.2 APIs. When the kernel is
configured with CONFIG_XDP_SOCKETS=y, the build fails with the following errors:

1)
drivers/net/ethernet/intel/ice/ice_xsk.c:936:14: error: too few arguments to function 'ice_alloc_rx_bufs_zc'
|   936 |   failure = !ice_alloc_rx_bufs_zc(rx_ring, cleaned_count);
|       |

This was introduced by the backport of upstream commit [1]. Current codebase
still makes use of the ice_alloc_rx_bufs_fast_zc() interface that was later
removed, so use this instead of the ice_alloc_rx_bufs_zc() call introduced
by [1].

2)
drivers/net/ethernet/intel/ice/ice_xsk.c:542:20: error: 'struct ice_rxq_stats' has no member named 'page_reuse_count'
|   542 |   rx_ring->rx_stats.page_reuse_count++;
|       |

In current codebase, ice_rxq_stats structure has no page_reuse_count member, so
remove this call.

[1] https://github.com/torvalds/linux/commit/5bb0c4b5eb61d939fed0b27d11fb91fb85769c9a

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>