MLK-13470 mfd: max17135: export symbols to fix build error as a module
commit 54dba2825d5f8a906d0632ddbe23ae8a64a0152b from
https://source.codeaurora.org/external/imx/linux-imx.git

export symbols to fix build error as a module:

ERROR: "max17135_reg_read" [drivers/hwmon/max17135-hwmon.ko] undefined!

Signed-off-by: Julien Olivain <julien.olivain@nxp.com>
Acked-by: Robby Cai <robby.cai@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>