ASoC-fsl_ssi: fixed compilation errors
commit 0cb0fb10f7e85d8e1decbbf38c87e348a60199e4 from
https://source.codeaurora.org/external/imx/linux-imx.git

As per commit 8bc84a3344ca ("ASoC: fsl_ssi: Rename i2smode to i2s_net")
and
commit a818aa5f967b ("ASoC: fsl_ssi: Rename registers and fields macros")
made changes to fix the compilation errors.

sound/soc/fsl/fsl_ssi.c: In function ‘fsl_ssi_hw_params’:
sound/soc/fsl/fsl_ssi.c:808:15: error: ‘ssi_private’ undeclared (first use in this function); did you mean ‘PG_private’?
  u8 i2smode = ssi_private->i2s_mode;
               ^~~~~~~~~~~
               PG_private
sound/soc/fsl/fsl_ssi.c:808:15: note: each undeclared identifier is reported only once for each function it appears in
sound/soc/fsl/fsl_ssi.c:810:20: error: ‘CCSR_SSI_SCR’ undeclared (first use in this function); did you mean ‘REG_SSI_SCR’?
  regmap_read(regs, CCSR_SSI_SCR, &scr_val);
                    ^~~~~~~~~~~~
                    REG_SSI_SCR
sound/soc/fsl/fsl_ssi.c:811:22: error: ‘CCSR_SSI_SCR_SSIEN’ undeclared (first use in this function); did you mean ‘SSI_SCR_SSIEN’?
  enabled = scr_val & CCSR_SSI_SCR_SSIEN;
                      ^~~~~~~~~~~~~~~~~~
                      SSI_SCR_SSIEN
sound/soc/fsl/fsl_ssi.c:844:14: error: ‘CCSR_SSI_SCR_I2S_MODE_NORMAL’ undeclared (first use in this function); did you mean ‘SSI_SCR_I2S_MODE_NORMAL’?
    i2smode = CCSR_SSI_SCR_I2S_MODE_NORMAL |
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
              SSI_SCR_I2S_MODE_NORMAL
sound/soc/fsl/fsl_ssi.c:845:5: error: ‘CCSR_SSI_SCR_NET’ undeclared (first use in this function); did you mean ‘SSI_SCR_NET’?
     CCSR_SSI_SCR_NET;
     ^~~~~~~~~~~~~~~~
     SSI_SCR_NET
In file included from ./include/sound/soc.h:20,
                 from sound/soc/fsl/fsl_ssi.c:50:
sound/soc/fsl/fsl_ssi.c:851:26: error: ‘CCSR_SSI_SCR_I2S_MODE_MASK’ undeclared (first use in this function); did you mean ‘SSI_SCR_I2S_MODE_MASK’?
       CCSR_SSI_SCR_NET | CCSR_SSI_SCR_I2S_MODE_MASK,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/regmap.h:77:36: note: in definition of macro ‘regmap_update_bits’
  regmap_update_bits_base(map, reg, mask, val, NULL, false, false)
                                    ^~~~
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_ssi.o' failed
make[3]: *** [sound/soc/fsl/fsl_ssi.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/fsl' failed
make[2]: *** [sound/soc/fsl] Error 2
scripts/Makefile.build:546: recipe for target 'sound/soc' failed
make[1]: *** [sound/soc] Error 2
Makefile:1052: recipe for target 'sound' failed
make: *** [sound] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>