drm/i2c: adv7511: add missing include to drm/drm_probe_helper.h
commit 315d8ed241f8f6e2b2df5bb880b5e1b61a54cb58 from
https://github.com/Xilinx/linux-xlnx.git

Otherwise, the compiler complains about not being able to find the
`drm_helper_hpd_irq_event` symbol:

```
drivers/gpu/drm/i2c/adv7511.c: In function 'adv7511_irq_process':
drivers/gpu/drm/i2c/adv7511.c:450:3: error: implicit declaration of function 'drm_helper_hpd_irq_event' [-Werror=implicit-function-declaration]
  450 |   drm_helper_hpd_irq_event(adv7511->encoder->dev);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Florian Klink <flokli@flokli.de>
Reviewed-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Yaliang Wang <Yaliang.Wang@windriver.com>