crypto: caam - fix building job ring as module
commit 9335f72011fe75f77b1e47c6c4e243ead7f6c05b from
http://source.codeaurora.org/external/qoriq/qoriq-components/linux

In case job ring is built as module, the shared descriptors libraries
also have to be built as modules - otherwise the linking will fail:
[...]
ERROR: "cnstr_shdsc_rfc4106_encap" [drivers/crypto/caam/caam_jr.ko] undefined!
ERROR: "cnstr_shdsc_aead_null_decap" [drivers/crypto/caam/caam_jr.ko] undefined!
ERROR: "cnstr_shdsc_gcm_encap" [drivers/crypto/caam/caam_jr.ko] undefined!
[...]

Fixes: a9ade076ed8b ("crypto: caam - duplicate files linking (kernel 4.14 sync)")
Signed-off-by: Horia Geantă <horia.geanta@nxp.com>
Signed-off-by: Zhantao Tang <zhantao.tang@windriver.com>