Revert "ice: Support XDP UMEM wake up mechanism"
This reverts commit 2c318c554a703724b1c5eb6cc4a8b4635a6ef019.

The ice ethernet driver in LTS19 was updated to the 5.12 codebase in
LINUXEXEC-10558 and adjusted to match various 5.2 APIs. It also added this
commit that relies on xsk_umem_uses_need_wakeup() API, which is not implemented
in 5.2 kernel. This currently causes the following build error when
CONFIG_XDP_SOCKETS=y:
drivers/net/ethernet/intel/ice/ice_xsk.c:941:6: error: implicit declaration of function 'xsk_umem_uses_need_wakeup' [-Werror=implicit-function-declaration]
|   941 |  if (xsk_umem_uses_need_wakeup(rx_ring->xsk_umem)) {
|       |      ^~~~~~~~~~~~~~~~~~~~~~~~~

To fix this, revert this commit, as the need_wakeup AF_XDP feature is not
implemented in 5.2.

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>