clk: zynqmp: Add missing checking of eemi_ops
commit 79785f65d157e110e033284f3eaec2dce84b7e59 from
https://github.com/Xilinx/linux-xlnx.git

Check if eemi_ops are properly initialized. If not error out.

The issue is reported by smatch like
  CHECK   drivers/clk/zynqmp/clk-mux-zynqmp.c
drivers/clk/zynqmp/clk-mux-zynqmp.c:52 zynqmp_clk_mux_get_parent()
 error: 'eemi_ops' dereferencing possible ERR_PTR()
drivers/clk/zynqmp/clk-mux-zynqmp.c:76 zynqmp_clk_mux_set_parent()
 error: 'eemi_ops' dereferencing possible ERR_PTR()

Signed-off-by: Michal Simek <michal.simek@xilinx.com>
State: pending
Signed-off-by: Yaliang Wang <Yaliang.Wang@windriver.com>