media: v4l2-async: Fix compilation errors
commit 1983b456d861e7249a230f5e9ebda5c632a85687 from
https://source.codeaurora.org/external/imx/linux-imx.git

As per commit 4e48afecd5ee ("media: v4l2-async: simplify v4l2_async_subdev
structure"), make changes to fix the compilation errors.

drivers/media/platform/mxc/subdev/mx6s_capture.c: In function ‘subdev_notifier_bound’:
drivers/media/platform/mxc/subdev/mx6s_capture.c:1688:31: error: ‘csi_dev->asd.match.fwnode’ is a pointer; did you mean to use ‘->’?
  if (csi_dev->asd.match.fwnode.fwnode == dev_fwnode(subdev->dev))
                               ^
                               ->
drivers/media/platform/mxc/subdev/mx6s_capture.c: In function ‘mx6sx_register_subdevs’:
drivers/media/platform/mxc/subdev/mx6s_capture.c:1765:28: error: ‘csi_dev->asd.match.fwnode’ is a pointer; did you mean to use ‘->’?
   csi_dev->asd.match.fwnode.fwnode = of_fwnode_handle(rem);
                            ^
                            ->
scripts/Makefile.build:309: recipe for target 'drivers/media/platform/mxc/subdev/mx6s_capture.o' failed
make[4]: *** [drivers/media/platform/mxc/subdev/mx6s_capture.o] Error 1
drivers/media/platform/mxc/subdev/mxc_mipi_csi.c: In function ‘subdev_notifier_bound’:
drivers/media/platform/mxc/subdev/mxc_mipi_csi.c:895:29: error: ‘state->asd.match.fwnode’ is a pointer; did you mean to use ‘->’?
  if (state->asd.match.fwnode.fwnode == dev_fwnode(subdev->dev))
                             ^
                             ->
drivers/media/platform/mxc/subdev/mxc_mipi_csi.c: In function ‘mipi_csis_subdev_host’:
drivers/media/platform/mxc/subdev/mxc_mipi_csi.c:968:26: error: ‘state->asd.match.fwnode’ is a pointer; did you mean to use ‘->’?
   state->asd.match.fwnode.fwnode = of_fwnode_handle(rem);
                          ^
scripts/Makefile.build:309: recipe for target 'drivers/media/platform/mxc/subdev/mxc_mipi_csi.o' failed
make[4]: *** [drivers/media/platform/mxc/subdev/mxc_mipi_csi.o] Error 1
  CC      drivers/media/v4l2-core/v4l2-device.o

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>