MLK-22299 pci: imx: fix build error when CONFIG_PM_SLEEP=n
commit 4c53329d0fcb7c812d8e219ca8c0ccdc01c42368 from
https://source.codeaurora.org/external/imx/linux-imx.git

drivers/pci/controller/dwc/pci-imx6.c:2826:2: error: implicit
declaration of function ‘pci_imx_set_msi_en’
[-Werror=implicit-function-declaration]
pci_imx_set_msi_en(&pci->pp);
^
drivers/pci/controller/dwc/pci-imx6.c: At top level:
drivers/pci/controller/dwc/pci-imx6.c:2857:10: error:
‘pci_imx_pm_ops’ undeclared here (not in a function)
.pm = &pci_imx_pm_ops,
    ^
cc1: some warnings being treated as errors

Signed-off-by: Richard Zhu <hongxing.zhu@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>