usb: typec: add max_snk_mv/ma/mw
commit 0cfefed6576b6cf7bca89e74fdd7595ad51ed8da from
https://source.codeaurora.org/external/imx/linux-imx.git

This patch add max_snk_mv/ma/mw to fix the below
compilation error.

drivers/usb/typec/tcpci.c:707:15: error: ‘struct tcpc_config’ has no member named ‘max_snk_mv’
          &tcfg->max_snk_mv) ||
               ^~
drivers/usb/typec/tcpci.c:709:13: error: ‘struct tcpc_config’ has no member named ‘max_snk_ma’
        &tcfg->max_snk_ma) ||
             ^~

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>