of: Fix of_populate_phandle_cache compilation error
When merging tag 'v4.18.10' into v4.18/standard/base, 05a9931 "of: fix phandle
cache creation for DTs with no phandles" from v4.18.10 introduces an undefined
label "out" and causes the follow compilation error.

drivers/of/base.c: In function 'of_populate_phandle_cache':
drivers/of/base.c:124:3: error: label 'out' used but not defined
   goto out;
   ^~~~

This is because the base of 05a9931 has been modified by b75caf0 "of: allocate /
free phandle cache outside of the devtree_lock".

This patch picks a part of
https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/commit/?h=
linux-4.18.y-rt&id=9866102318991051e5e99085d3c88d6483ee70d4
to fix this error, and can be dropped when rebasing above 9866102.

Signed-off-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>