v4l: xilinx: sdi: Fix the uapi header license
commit a8d8fa6b18cfecab6d6fd65d6aac1a58d3d5bd78 from
https://github.com/Xilinx/linux-xlnx.git

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Yaliang Wang <Yaliang.Wang@windriver.com>