video: mxc: fbdev: mipi_dsi_northwest: Fix compilation error
commit 7ac3dd4ba8ad893e8f5680b79d9ca15e04bf5b2c from
https://source.codeaurora.org/external/imx/linux-imx.git

This patch fix the below compilation error.

rivers/video/fbdev/mxc/mipi_dsi_northwest.c: In function ‘mipi_dsi_suspend’:
drivers/video/fbdev/mxc/mipi_dsi_northwest.c:1487:2: error: implicit declaration of function ‘pinctrl_pm_select_sleep_state’ [-Werror=implicit-function-declaration]
  pinctrl_pm_select_sleep_state(dev);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/video/fbdev/mxc/mipi_dsi_northwest.c: In function ‘mipi_dsi_resume’:
drivers/video/fbdev/mxc/mipi_dsi_northwest.c:1494:2: error: implicit declaration of function ‘pinctrl_pm_select_default_state’; did you mean ‘irq_set_default_host’? [-Werror=implicit-function-declaration]
  pinctrl_pm_select_default_state(dev);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  irq_set_default_host
  AR      kernel/built-in.a
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/video/fbdev/mxc/mipi_dsi_northwest.o' failed
make[4]: *** [drivers/video/fbdev/mxc/mipi_dsi_northwest.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>