v4l: xilinx: events: Fix the uapi header license
commit 95bf30ae3ad2e35dbf0682a4e251846a3dc6db99 from
https://github.com/Xilinx/linux-xlnx.git

Error: missing "WITH Linux-syscall-note" for SPDX-License-Identifier

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
State: pending
Signed-off-by: Yaliang Wang <Yaliang.Wang@windriver.com>