ASoC: wm8960: fixed compilation error
commit dad082c01c3e4c67c438fdc69922dc49cc162499 from
https://source.codeaurora.org/external/imx/linux-imx.git

sound/soc/codecs/wm8960.c: In function ‘wm8960_set_bias_level_out3’:
sound/soc/codecs/wm8960.c:919:36: error: ‘codec’ undeclared (first use in this function); did you mean ‘cdev’?
    ret = wm8960_configure_clocking(codec);
                                    ^~~~~
                                    cdev
sound/soc/codecs/wm8960.c:919:36: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:305: recipe for target 'sound/soc/codecs/wm8960.o' failed
make[3]: *** [sound/soc/codecs/wm8960.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/codecs' failed
make[2]: *** [sound/soc/codecs] Error 2
scripts/Makefile.build:546: recipe for target 'sound/soc' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>