ASoC: fsl_ssi: fixed compilation errors
commit f89c6201fe9e9646e60fbd16032b0b68add21f38 from
https://source.codeaurora.org/external/imx/linux-imx.git

sound/soc/fsl/fsl_ssi.c: In function ‘fsl_ssi_shutdown’:
sound/soc/fsl/fsl_ssi.c:667:35: error: dereferencing pointer to incomplete type ‘struct fsl_ssi_private’
  clk_disable_unprepare(ssi_private->clk);
                                   ^~
sound/soc/fsl/fsl_ssi.c: In function ‘fsl_ssi_probe’:
sound/soc/fsl/fsl_ssi.c:1567:30: error: ‘ssi_private’ undeclared (first use in this function); did you mean ‘PG_private’?
  dev_set_drvdata(&pdev->dev, ssi_private);
                              ^~~~~~~~~~~
                              PG_private
sound/soc/fsl/fsl_ssi.c:1567:30: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_ssi.o' failed
make[3]: *** [sound/soc/fsl/fsl_ssi.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/fsl' failed
make[2]: *** [sound/soc/fsl] Error 2
scripts/Makefile.build:546: recipe for target 'sound/soc' failed
make[1]: *** [sound/soc] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>