video: mxsfb: Fix compilation error
commit 5efde09e6add901c6a5d3a0fccf52b821bcce3ab from
https://source.codeaurora.org/external/imx/linux-imx.git

This patch fix the below compilation error.

drivers/video/fbdev/mxsfb.c: In function ‘mxsfb_remove’:
drivers/video/fbdev/mxsfb.c:2377:22: error: passing argument 1 of ‘mxsfb_free_videomem’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  mxsfb_free_videomem(fb_info);
                      ^~~~~~~
drivers/video/fbdev/mxsfb.c:1509:52: note: expected ‘struct mxsfb_info *’ but argument is of type ‘struct fb_info *’
 static void mxsfb_free_videomem(struct mxsfb_info *host)

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>