ASoC-fsl_ssi: fixed compilation errors
commit 918a3a34707202cdf2c36286dfe2546ebbc29aa0 from
https://source.codeaurora.org/external/imx/linux-imx.git

As per commit a818aa5f967b ("ASoC: fsl_ssi: Rename registers and fields
macros"), made changes to fix the compilation errors.

sound/soc/fsl/fsl_ssi.c: In function ‘_fsl_ssi_set_dai_fmt’:
sound/soc/fsl/fsl_ssi.c:896:14: error: ‘regs’ undeclared (first use in this function)
  regmap_read(regs, CCSR_SSI_SCR, &scr);
              ^~~~
sound/soc/fsl/fsl_ssi.c:896:14: note: each undeclared identifier is reported only once for each function it appears in
sound/soc/fsl/fsl_ssi.c:896:20: error: ‘CCSR_SSI_SCR’ undeclared (first use in this function); did you mean ‘REG_SSI_SCR’?
  regmap_read(regs, CCSR_SSI_SCR, &scr);
                    ^~~~~~~~~~~~
                    REG_SSI_SCR
sound/soc/fsl/fsl_ssi.c:897:10: error: ‘CCSR_SSI_SCR_SYN’ undeclared (first use in this function); did you mean ‘SSI_SCR_SYN’?
  scr &= ~CCSR_SSI_SCR_SYN;
          ^~~~~~~~~~~~~~~~
          SSI_SCR_SYN
sound/soc/fsl/fsl_ssi.c:898:9: error: ‘CCSR_SSI_SCR_SYNC_TX_FS’ undeclared (first use in this function); did you mean ‘SSI_SCR_SYNC_TX_FS’?
  scr |= CCSR_SSI_SCR_SYNC_TX_FS;
         ^~~~~~~~~~~~~~~~~~~~~~~
         SSI_SCR_SYNC_TX_FS
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_ssi.o' failed
make[3]: *** [sound/soc/fsl/fsl_ssi.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc/fsl' failed
make[2]: *** [sound/soc/fsl] Error 2
scripts/Makefile.build:546: recipe for target 'sound/soc' failed
make[1]: *** [sound/soc] Error 2
Makefile:1052: recipe for target 'sound' failed
make: *** [sound] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>