MLK-11985-1 ARM: imx: gpc: fix coverity scan issues
commit f924f74eab5e68936952f4c4111ff8f295912b67 from
https://source.codeaurora.org/external/imx/linux-imx.git

Improve code to fix below warning:

copy_paste_error: i in of_clk_get(dev->of_node, i)
looks like a copy-paste error.

Signed-off-by: Anson Huang <Anson.Huang@freescale.com>
Signed-off-by: Leonard Crestez <leonard.crestez@nxp.com>
Signed-off-by: Arulpandiyan Vadivel <arulpandiyan_vadivel@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>