MLK-15004: ASoC: fixed compilation error
commit 122004f8004db35f2787c65878ee8f54d41a51c9 from
https://source.codeaurora.org/external/imx/linux-imx.git

Enable DMA workaround for fsl_spdif driver.

sound/soc/fsl/fsl_spdif.o: In function `fsl_spdif_remove':
fsl_spdif.c:(.text+0xb3c): undefined reference to `fsl_dma_workaround_free_info'
sound/soc/fsl/fsl_spdif.o: In function `fsl_spdif_hw_free':
fsl_spdif.c:(.text+0x1010): undefined reference to `clear_gpt_dma'
sound/soc/fsl/fsl_spdif.o: In function `fsl_spdif_probe':
fsl_spdif.c:(.text+0x1b98): undefined reference to `fsl_dma_workaround_alloc_info'
sound/soc/fsl/fsl_spdif.o: In function `fsl_spdif_hw_params':
fsl_spdif.c:(.text+0x1fa8): undefined reference to `configure_gpt_dma'
Makefile:1032: recipe for target 'vmlinux' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>