tty: serial: imx: Fix compilation error for 4.19
commit 878a2394dc31eead6668fa4480d720619740df17 from
https://source.codeaurora.org/external/imx/linux-imx.git

As per commit 4444dcf1fe7e ("serial: imx: use u32 variables with matching
names for registers"), make changes to fix the below compilation error.

drivers/tty/serial/imx.c: In function ‘imx_uart_stop_rx’:
drivers/tty/serial/imx.c:486:2: error: ‘temp’ undeclared (first use in this function); did you mean ‘sem’?
  temp = readl(sport->port.membase + UCR1);
  ^~~~
  sem
drivers/tty/serial/imx.c:486:2: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:303: recipe for target 'drivers/tty/serial/imx.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>