of: phandle_cache merge fixup for preempt-rt
In yocto merge 5cc3fddf0e2a ("Merge branch 'v4.18/standard/base' into
v4.18/standard/preempt-rt/base") there was a conflict between the
backport of upstream b8a9ac1a5b99 ("of: of_node_get()/of_node_put() nodes
held in phandle cache") and the rt-specific commit b75caf08b721 ("of:
allocate / free phandle cache outside of the devtree_lock")

Unfortunately the conflict resolution left a shadow variable introduced
by the rt patch as undefined, resulting in:

drivers/of/base.c:120:2: error: 'shadow' undeclared (first use in this function)
  shadow = phandle_cache;
  ^~~~~~

drivers/of/base.c: In function 'of_populate_phandle_cache':
drivers/of/base.c:182:7: warning: 'shadow' is used uninitialized in this function [-Wuninitialized]

Here we create a merge fix-up that basically aligns the impacted code to
match what is currently found in the 4.19-rt (as of v4.19.15-rt12).

Reported-by: Yue Tao <Yue.Tao@windriver.com>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>