MLK-12392: arm: imx6q: fix lpddr2 build error if SMP is disabled
commit 56f1929da2341afbdbae1220bc627359ccd562d9 from
https://source.codeaurora.org/external/imx/linux-imx.git

Fix build error if CONFIG_SMP is disabled:

arch/arm/mach-imx/busfreq_lpddr2.c: In function ‘update_lpddr2_freq_smp’:
arch/arm/mach-imx/busfreq_lpddr2.c:236:67: error: ‘me’ undeclared (first
use in this function)
  printk(KERN_DEBUG "Bus freq set to %d done! cpu=%d\n", ddr_rate, me);

Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>
Signed-off-by: Frank Li <Frank.Li@nxp.com>
Signed-off-by: Arulpandiyan Vadivel <arulpandiyan_vadivel@mentor.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>