fs: yaffs2: includes the missing header file
To fix the following build error:
  fs/yaffs2/yaffs_vfs.c: In function 'yaffs_mknod':
  fs/yaffs2/yaffs_vfs.c:1252:2: error: implicit declaration of function 'current_fsuid' [-Werror=implicit-function-declaration]
    uid_t uid = YCRED_FSUID();
    ^

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>