Revert "x86: Use CONFIG_PREEMPTION"
This reverts commit 41bbdde13b435400816397a47e84fa697934c253.

The reverted patch causes the following build failure.
tmp-glibc/work-shared/intel-x86-64/kernel-source/include/linux/preempt.h:190:3:
error: implicit declaration of function '__preempt_schedule'
[-Werror=implicit-function-declaration]

The reverted patch should have been used with b8d3349803ba
("sched/rt, Kconfig: Unbreak def/oldconfig with CONFIG_PREEMPT=y") which fixes
a50a3f4b6a31 ("sched/rt, Kconfig: Introduce CONFIG_PREEMPT_RT") which is not
included in 5.2.29. So we simply revert 41bbdde13b43.

Signed-off-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>