workqueue: Fix missing transition to raw lock
For the following build failure.

kernel/workqueue.c:4336:17: error: passing argument 1 of 'rt_spin_lock' from
incompatible pointer type [-Werror=incompatible-pointer-types]
4336 | spin_lock_irq(&wq_mayday_lock);
| ^~~~~~~~~~~~~~~
kernel/workqueue.c:4338:19: error: passing argument 1 of 'rt_spin_unlock' from
incompatible pointer type [-Werror=incompatible-pointer-types]
4338 | spin_unlock_irq(&wq_mayday_lock);
| ^~~~~~~~~~~~~~~

Signed-off-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>